#routing.provider=crowfly
routing.provider=osrm
#routing.osrm.base-url=http://localhost:5000
routing.osrm.base-url=https://router.project-osrm.org
routing.osrm.connect-timeout=2s
routing.osrm.request-timeout=10s
routing.osrm.max-locations=100

# CORS Configuration (Overridden by CORS_ALLOWED_ORIGINS in production)
cors.allowed-origins=http://localhost:5173,http://localhost:4173
