#routing.provider=crowfly
routing.provider=osrm
#routing.osrm.base-url=http://localhost:5000
routing.osrm.base-url=https://router.project-osrm.org
routing.osrm.connect-timeout=6s
routing.osrm.request-timeout=20s
routing.osrm.max-locations=100

# CORS Configuration (Overridden by CORS_ALLOWED_ORIGINS in production)
cors.allowed-origins=http://localhost:5173,http://localhost:4173

# In-Memory Cache Configuration
routing.cache.enabled=true
routing.cache.ttl=4h
routing.cache.max-entries=500

# Geometry Concurrency Configuration
routing.geometry.parallelism=5
